### ISSUE TITLE
4.0.0 Invalid RegEx 

### ISSUE THREAD

**Issue by foxriver76** [peter-murray/node-hue-api#151]
When using the module in 4.0.0 it throws the following errors, using Node 8.17.0:

```
2019-12-28 01:06:02.419  - error:  host.ioBroker-Rock64 Caught by controller[0]:  /opt/iobroker/node_modules/iobroker.hue/node_modules/node-hue-api/lib/model/timePatterns/HueTime.js:15
--
2019-12-28 01:06:02.421  - error: host.ioBroker-Rock64 Caught by controller[0]: const TIME_REGEX = new RegExp(dateTimeUtil.getTimePattern());
2019-12-28 01:06:02.422  - error: host.ioBroker-Rock64 Caught by controller[0]:                    ^
2019-12-28 01:06:02.422  - error: host.ioBroker-Rock64 Caught by controller[0]: SyntaxError: Invalid regular expression: /(?[0-9]{2}):(?[0-9]{2}):(?[0-9]{2})/: Invalid group
2019-12-28 01:06:02.423  - error: host.ioBroker-Rock64 Caught by controller[0]:     at new RegExp ()
2019-12-28 01:06:02.424  - error: host.ioBroker-Rock64 Caught by controller[0]:     at Object. (/opt/iobroker/node_modules/iobroker.hue/node_modules/node-hue-api/lib/model/timePatterns/HueTime.js:15:20)
2019-12-28 01:06:02.425  - error: host.ioBroker-Rock64 Caught by controller[0]:     at Module._compile (module.js:653:30)
2019-12-28 01:06:02.426  - error: host.ioBroker-Rock64 Caught by controller[0]:     at Object.Module._extensions..js (module.js:664:10)
2019-12-28 01:06:02.427  - error: host.ioBroker-Rock64 Caught by controller[0]:     at Module.load (module.js:566:32)
2019-12-28 01:06:02.428  - error: host.ioBroker-Rock64 Caught by controller[0]:     at tryModuleLoad (module.js:506:12)
2019-12-28 01:06:02.428  - error: host.ioBroker-Rock64 Caught by controller[0]:     at Function.Module._load (module.js:498:3)
2019-12-28 01:06:02.429  - error: host.ioBroker-Rock64 Caught by controller[0]:     at Module.require (module.js:597:17)
2019-12-28 01:06:02.430  - error: host.ioBroker-Rock64 Caught by controller[0]:     at require (internal/module.js:11:18)
2019-12-28 01:06:02.431  - error: host.ioBroker-Rock64 Caught by controller[0]:     at Object. (/opt/iobroker/node_modules/iobroker.hue/node_modules/node-hue-api/lib/model/timePatterns/AbsoluteTime.js:4:15)
```

**Comment by foxriver76** [comment]
I see - you've defined nodejs 10 as min engine, so guess thats my fault. ;-)
