### ISSUE TITLE
NodeJS Regex crash

### ISSUE THREAD

**Issue by danTheWizard** [peter-murray/node-hue-api#164]
Hello Mr.Murray.

The library works fantastic in my local environment.
When pushed to a remote server running Node I encounter the following error that prevents starting the server: 
node_modules/node-hue-api/lib/model/timePatterns/HueTime.js:15
const TIME_REGEX = new RegExp(dateTimeUtil.getTimePattern());
                   ^

SyntaxError: Invalid regular expression: /(?<hours>[0-9]{2}):(?<minutes>[0-9]{2}):(?<seconds>[0-9]{2})/: Invalid group
    at new RegExp (<anonymous>)
    at Object.<anonymous> (/home/ubuntu/node/node_modules/node-hue-api/lib/model/timePatterns/HueTime.js:15:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/node/node_modules/node-hue-api/lib/model/timePatterns/AbsoluteTime.js:4:15)

I am currently trying to find a solution. Perhaps I am missing a necessary library? 

Thanks, and I appreciate the work you've put in.

**Comment by danTheWizard** [comment]
Node update and server restart appears to have solved the issue. 
My apologies.

**Comment by peter-murray** [comment]
The regex I use for time patterns is compatible with Node.js 10+

**Comment by danTheWizard** [comment]
I'm not sure what the issue could have been but it has since been resolved with a simple restart of the VM.

My apologies for the unnecessary ticket.

Your work is much appreciated :)

**Comment by peter-murray** [comment]
Cheers, no problems, glad you have it working.
